import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Modal from "../components/Modal";

export default function Home() {
  const [showModal, setShowModal] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Implementing Modal in Next.js using createPortal</h2>
        <button onClick={() => setShowModal(true)} className="btn">
          Modal
        </button>
        <Modal show={showModal} onClose={() => setShowModal(false)}>
          Portal은 부모 컴포넌트의 DOM 계층 구조 바깥에 있는 DOM 노드로 자식을
          렌더링하는 최고의 방법을 제공합니다. 첫 번째 인자(child)는 엘리먼트,
          문자열, 혹은 fragment와 같은 어떤 종류이든 렌더링할 수 있는 React
          자식입니다. 두 번째 인자(container)는 DOM 엘리먼트입니다.
        </Modal>
      </main>
    </>
  );
}
